### PR TITLE
feat: updates models

### PR DESCRIPTION
**Pull request by sbracellari**

### CODE REVIEW

**Comment by dorisgjata** [comment]
What's the difference of having specific rowmappers in creator and location vs having them in the artwork? I guess if we need to get the objects individually, but other than that they should do the same thing right?

**Comment by dorisgjata** [comment]
I don't see any row mappers for tours and favorites. Is that logic handled in the service?

**Comment by sbracellari** [comment]
> What's the difference of having specific rowmappers in creator and location vs having them in the artwork? I guess if we need to get the objects individually, but other than that they should do the same thing right?

They achieve the same thing. I mainly did it because it cleaned up the artwork mapper.

**Comment by sbracellari** [comment]
> I don't see any row mappers for tours and favorites. Is that logic handled in the service?

Yeah. I had to do some stuff in the service to return that information properly.

**Comment by dorisgjata** [comment]
Merged the main one

**Pull request closed without merging**
